In [1]:
import pandas as pd

In [3]:
accidents = pd.read_csv('tt.csv',engine='python',encoding='cp949')

In [4]:
accidents

      시도  시군구      시간대  발생건수  사망자수  부상자수  중상   경상  부상신고
0     서울  종로구  00시-02시    76     1   114  23   83     8
1     서울  종로구  02시-04시    40     0    60  11   45     4
2     서울  종로구  04시-06시    43     0    58  13   37     8
3     서울  종로구  06시-08시    64     2    93  20   65     8
4     서울  종로구  08시-10시    94     0   132  29   71    32
5     서울  종로구  10시-12시   108     0   136  30   92    14
6     서울  종로구  12시-14시   111     1   137  30   92    15
7     서울  종로구  14시-16시   118     0   168  28  115    25
8     서울  종로구  16시-18시   105     0   138  28   91    19
9     서울  종로구  18시-20시   131     0   162  36  107    19
10    서울  종로구  20시-22시   115     1   167  34  121    12
11    서울  종로구  22시-24시   129     1   181  38  120    23
12    서울   중구  00시-02시    64     0    98  29   58    11
13    서울   중구  02시-04시    57     0    73  16   50     7
14    서울   중구  04시-06시    51     3    58  24   28     6
15    서울   중구  06시-08시    60     0    95  19   68     8
16    서울   중구  08시-10시    92     0   118  32   73    13
17    서울   중구  10시-12시   131     1   167  54   96    17
18    서울   중구  12시-14시   125     0   165  34  110    21
19    서울   중구  14시-16시   118     0   159  39  103    17
20    서울   중구  16시-18시   121     1   173  40  117    16
21    서울   중구  18시-20시   119     3   152  31  106    15
22    서울   중구  20시-22시   107     1   138  36   85    17
23    서울   중구  22시-24시    83     0   110  26   68    16
24    서울  용산구  00시-02시    93     3   142  37  101     4
25    서울  용산구  02시-04시    71     1   103  24   69    10
26    서울  용산구  04시-06시    65     2    92  25   58     9
27    서울  용산구  06시-08시    81     2   111  23   81     7
28    서울  용산구  08시-10시   123     2   149  33  110     6
29    서울  용산구  10시-12시   120     1   168  33  120    15
...   ..  ...      ...   ...   ...   ...  ..  ...   ...
2682  울산   북구  12시-14시    45     1    78  24   51     3
2683  울산   북구  14시-16시    67     1   104  28   69     7
2684  울산   북구  16시-18시    77     1   113  29   80     4
2685  울산   북구  18시-20시    79     2   113  36   66    11
2686  울산   북구  20시-22시    57     0    83  21   53     9
2687  울산   북구  22시-24시    59     4    85  21   58     6
2688  울산  울주군  00시-02시    23     0    42  13   25     4
2689  울산  울주군  02시-04시    15     0    19   5   13     1
2690  울산  울주군  04시-06시    31     4    39  13   19     7
2691  울산  울주군  06시-08시    84     5   128  39   81     8
2692  울산  울주군  08시-10시   100     2   162  31  111    20
2693  울산  울주군  10시-12시    82     2   151  40   93    18
2694  울산  울주군  12시-14시    69     1   137  37   81    19
2695  울산  울주군  14시-16시    89     3   145  33  103     9
2696  울산  울주군  16시-18시   107     0   154  43   88    23
2697  울산  울주군  18시-20시    97     3   143  43   89    11
2698  울산  울주군  20시-22시    80     4   105  32   65     8
2699  울산  울주군  22시-24시    53     0    83  25   53     5
2700  세종   세종  00시-02시    34     3    47  15   32     0
2701  세종   세종  02시-04시    16     2    17  10    7     0
2702  세종   세종  04시-06시    18     0    22   5   15     2
2703  세종   세종  06시-08시    58     3    93  28   63     2
2704  세종   세종  08시-10시    93     1   135  40   92     3
2705  세종   세종  10시-12시    64     2    86  26   57     3
2706  세종   세종  12시-14시    71     1   103  24   78     1
2707  세종   세종  14시-16시    81     0   114  29   80     5
2708  세종   세종  16시-18시   102     5   137  35   94     8
2709  세종   세종  18시-20시   112     1   168  34  131     3
2710  세종   세종  20시-22시    87     1   134  19  114     1
2711  세종   세종  22시-24시    59     1    86  23   61     2

[2712 rows x 9 columns]

In [6]:
accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2712 entries, 0 to 2711
Data columns (total 9 columns):
시도      2712 non-null object
시군구     2712 non-null object
시간대     2712 non-null object
발생건수    2712 non-null int64
사망자수    2712 non-null int64
부상자수    2712 non-null int64
중상      2712 non-null int64
경상      2712 non-null int64
부상신고    2712 non-null int64
dtypes: int64(6), object(3)
memory usage: 190.8+ KB

In [22]:
accidents.describe(include='int64')

,발생건수,사망자수,부상자수,중상,경상,부상신고
count,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000
mean,80.069322,1.394174,119.113938,27.381268,83.890487,7.842183
std,89.648963,1.626463,134.803960,27.218569,100.113161,12.016687
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,18.000000,0.000000,27.000000,8.000000,16.000000,1.000000
50%,52.000000,1.000000,78.000000,20.000000,52.000000,3.000000
75%,108.000000,2.000000,158.000000,36.000000,110.000000,10.000000
max,740.000000,14.000000,1148.000000,196.000000,923.000000,99.000000

In [17]:
accidents.describe(include='all')

,시도,시군구,시간대,발생건수,사망자수,부상자수,중상,경상,부상신고
count,2712,2712,2712,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000,2712.000000
unique,17,206,12,NaN,NaN,NaN,NaN,NaN,NaN
top,경기,동구,06시-08시,NaN,NaN,NaN,NaN,NaN,NaN
freq,372,72,229,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,80.069322,1.394174,119.113938,27.381268,83.890487,7.842183
std,NaN,NaN,NaN,89.648963,1.626463,134.803960,27.218569,100.113161,12.016687
min,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,18.000000,0.000000,27.000000,8.000000,16.000000,1.000000
50%,NaN,NaN,NaN,52.000000,1.000000,78.000000,20.000000,52.000000,3.000000
75%,NaN,NaN,NaN,108.000000,2.000000,158.000000,36.000000,110.000000,10.000000
max,NaN,NaN,NaN,740.000000,14.000000,1148.000000,196.000000,923.000000,99.000000

In [18]:
accidents.head(10)

   시도  시군구      시간대  발생건수  사망자수  부상자수  중상   경상  부상신고
0  서울  종로구  00시-02시    76     1   114  23   83     8
1  서울  종로구  02시-04시    40     0    60  11   45     4
2  서울  종로구  04시-06시    43     0    58  13   37     8
3  서울  종로구  06시-08시    64     2    93  20   65     8
4  서울  종로구  08시-10시    94     0   132  29   71    32
5  서울  종로구  10시-12시   108     0   136  30   92    14
6  서울  종로구  12시-14시   111     1   137  30   92    15
7  서울  종로구  14시-16시   118     0   168  28  115    25
8  서울  종로구  16시-18시   105     0   138  28   91    19
9  서울  종로구  18시-20시   131     0   162  36  107    19

In [19]:
accidents.tail(10)

      시도 시군구      시간대  발생건수  사망자수  부상자수  중상   경상  부상신고
2702  세종  세종  04시-06시    18     0    22   5   15     2
2703  세종  세종  06시-08시    58     3    93  28   63     2
2704  세종  세종  08시-10시    93     1   135  40   92     3
2705  세종  세종  10시-12시    64     2    86  26   57     3
2706  세종  세종  12시-14시    71     1   103  24   78     1
2707  세종  세종  14시-16시    81     0   114  29   80     5
2708  세종  세종  16시-18시   102     5   137  35   94     8
2709  세종  세종  18시-20시   112     1   168  34  131     3
2710  세종  세종  20시-22시    87     1   134  19  114     1
2711  세종  세종  22시-24시    59     1    86  23   61     2

In [20]:
accidents.sample(10)

      시도   시군구      시간대  발생건수  사망자수  부상자수  중상   경상  부상신고
785   경기  동두천시  10시-12시    55     2    75  16   59     0
1527  전북   부안군  12시-14시    42     1    70  18   52     0
1478  전북   장수군  06시-08시     5     0    11   6    5     0
477   부산   사상구  18시-20시   122     1   187  48   99    40
640   경기   시흥시  08시-10시   262     2   383  68  299    16
105   서울  서대문구  18시-20시   123     0   149  43   85    21
2210  경남   남해군  18시-20시    17     2    25  13   11     1
1651  전남   고흥군  22시-24시     9     0    10   3    7     0
2198  경남   사천시  16시-18시    89     0   163  39   95    29
1157  충북   진천군  22시-24시    36     3    52  11   40     1